---
version: '3'

services:
  selenium:
    image: selenium/standalone-firefox
    # point webdriver to http://selenium:4444
    # to watch selenium go, http://localhost:7900/?password=secret
    ports:
      - '9200:4444'
      - '7900:7900'
    shm_size: 2G
    networks:
      - tundra
    volumes:
      - .:/u/app
networks:
  tundra:
    ipam:
      config:
        - subnet: '192.168.53.72/28'
